//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using System.Data.SQLite;
using System;

namespace WPFApp1
{
    public class SQLiteDb
    {
        public void Create()
        {

            SQLiteConnection conn = new SQLiteConnection("Data Source=Project4DB.sqlite;Version=3;");
            conn.Open();
            conn.Close();

        }
    }

}
