//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using System.Data.SQLite;
using System;

namespace WPFApp1
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }

        public void Create()
        {
            SQLiteConnection conn = new SQLiteConnection("Data Source=Project4DB.sqlite;Version=3;");
            conn.Open();
            conn.Close();

        }
        public partial class rating
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }

        [NotNull]
        public String recipe_name { get; set; }

        [NotNull]
        public Int64 rating { get; set; }

    }

    public partial class recept
    {
        [NotNull]
        public Int64 Id { get; set; }

        [NotNull]
        public String recipe_name { get; set; }

        [NotNull]
        public String category { get; set; }

        [NotNull]
        public String ingredient_list { get; set; }

        [NotNull]
        public String preparation { get; set; }

    }

    public partial class user
    {
        [NotNull]
        public Int64 Id { get; set; }

        [NotNull]
        public String user_name { get; set; }

        [NotNull]
        public String password { get; set; }

    }

}
